version: '3.1'
services:
    db:
        image: mariadb
        container_name: mydb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: askbot
            MYSQL_USER: askbot
            MYSQL_PASSWORD: askbot
        tty: false
        stdin_open: false
    proxy:
        image: nginx
        container_name: proxy
        restart: always
        volumes:
            - ./conf/proxy.conf:/etc/nginx/nginx.conf:ro
            - ./conf/cert.crt:/etc/nginx/cert.crt:ro
            - ./conf/cert.key:/etc/nginx/cert.key:ro
        depends_on:
            - "qa"
        ports:
            - "80:80"
            - "443:443"
    qa:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SRC_DIR: .
        container_name: askbot
        depends_on:
            - "db"
#        ports:
#            - "81:80"