version: '3.1'
services:
    db:
        image: mariadb
        container_name: mydb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: askbot
            MYSQL_USER: askbot
            MYSQL_PASSWORD: askbot
        tty: false
        stdin_open: false
    qa:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SRC_DIR: .
        container_name: askbot
        depends_on:
            - "db"
        ports:
            - "81:80"